# Generated by Django 3.0 on 2019-12-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviefollow'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='moviesfollowed',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
