# Generated by Django 3.0 on 2019-12-23 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_moviesfollowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='FollowedBy',
            field=models.ManyToManyField(related_name='_account_FollowedBy_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='Following',
            field=models.ManyToManyField(related_name='_account_Following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User being followed+', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User following+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
