# Generated by Django 3.0 on 2019-12-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_director_game_genre_movie_publication_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='Publication_name',
            new_name='publication_name',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='Star_dob',
            new_name='star_dob',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='Star_name',
            new_name='star_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Publication_description',
        ),
        migrations.RemoveField(
            model_name='star',
            name='Star_description',
        ),
        migrations.AddField(
            model_name='game',
            name='game_avgreview',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_avgreview',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='star',
            name='star_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_nor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_totalreview',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_nor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_runningtime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_totalreview',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=400)),
                ('show_date', models.DateField(verbose_name='first episode released')),
                ('show_description', models.TextField(blank=True)),
                ('show_runningtime', models.DurationField()),
                ('show_totalepisode', models.IntegerField(default=1)),
                ('show_totalreview', models.IntegerField(default=0)),
                ('show_nor', models.IntegerField(default=0)),
                ('show_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='tvshows/')),
                ('show_avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('show_director', models.ManyToManyField(to='base.Director')),
                ('show_genre', models.ManyToManyField(to='base.Genre')),
                ('show_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Publication')),
                ('show_star', models.ManyToManyField(to='base.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=400)),
                ('episode_number', models.IntegerField()),
                ('episode_description', models.TextField(blank=True)),
                ('episode_date', models.DateField(verbose_name='Edisode Release Date')),
                ('episode_runningtime', models.DurationField()),
                ('episode_totalreview', models.IntegerField(default=0)),
                ('episode_nor', models.IntegerField(default=0)),
                ('episode_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='episodes/')),
                ('episode_avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('episode_director', models.ManyToManyField(to='base.Director')),
                ('episode_show_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TvShow')),
            ],
        ),
    ]
