# Generated by Django 3.0 on 2019-12-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('releasedate', models.DateField(verbose_name='first episode released')),
                ('description', models.TextField(blank=True)),
                ('runningtime', models.DurationField()),
                ('totalepisode', models.IntegerField(default=1)),
                ('totalreview', models.IntegerField(default=0)),
                ('nor', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='tvshows/')),
                ('avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('director', models.ManyToManyField(to='base.Director')),
                ('genre', models.ManyToManyField(to='base.Genre')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Publication')),
                ('star', models.ManyToManyField(to='base.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodename', models.CharField(max_length=400)),
                ('episodenumber', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('releasedate', models.DateField(verbose_name='Edisode Release Date')),
                ('runningtime', models.DurationField()),
                ('totalreview', models.IntegerField(default=0)),
                ('nor', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='episodes/')),
                ('avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('director', models.ManyToManyField(to='base.Director')),
                ('show_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.TvShow')),
            ],
        ),
    ]
