# Generated by Django 3.0 on 2019-12-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=400)),
                ('show_date', models.DateField(verbose_name='first episode released')),
                ('show_description', models.TextField(blank=True)),
                ('show_runningtime', models.DurationField()),
                ('show_totalepisode', models.IntegerField(default=1)),
                ('show_totalreview', models.IntegerField(default=0)),
                ('show_nor', models.IntegerField(default=0)),
                ('show_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='tvshows/')),
                ('show_avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('show_director', models.ManyToManyField(to='base.Director')),
                ('show_genre', models.ManyToManyField(to='base.Genre')),
                ('show_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Publication')),
                ('show_star', models.ManyToManyField(to='base.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=400)),
                ('episode_number', models.IntegerField()),
                ('episode_description', models.TextField(blank=True)),
                ('episode_date', models.DateField(verbose_name='Edisode Release Date')),
                ('episode_runningtime', models.DurationField()),
                ('episode_totalreview', models.IntegerField(default=0)),
                ('episode_nor', models.IntegerField(default=0)),
                ('episode_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='episodes/')),
                ('episode_avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('episode_director', models.ManyToManyField(to='base.Director')),
                ('episode_show_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.TvShow')),
            ],
        ),
    ]
