# Generated by Django 3.0 on 2019-12-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('releasedate', models.DateField(verbose_name='date released')),
                ('description', models.TextField(blank=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('totalreview', models.IntegerField(default=0)),
                ('nor', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='games/')),
                ('avgreview', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('genre', models.ManyToManyField(to='base.Genre')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Publication')),
            ],
        ),
    ]
