# Generated by Django 3.0 on 2019-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_avgreview',
            new_name='avgreview',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_nor',
            new_name='nor',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_publication',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_date',
            new_name='releasedate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_totalreview',
            new_name='totalreview',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_size',
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
