# Generated by Django 3.0 on 2019-12-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191215_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='avgreview',
            new_name='avgrating',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nor',
            new_name='totalrating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='totalreview',
        ),
    ]
