# Generated by Django 3.0 on 2019-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20191219_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='totalreview',
            field=models.IntegerField(default=0),
        ),
    ]
