# Generated by Django 3.0 on 2019-12-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_avgreview',
            new_name='avgreview',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_nor',
            new_name='nor',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_publication',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_date',
            new_name='releasedate',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_runningtime',
            new_name='runningtime',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_star',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_totalreview',
            new_name='totalreview',
        ),
    ]
