# Generated by Django 3.0 on 2019-12-15 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20191213_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='MovieReview',
        ),
    ]
