# Generated by Django 3.0 on 2019-12-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191215_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='nor',
            new_name='totalrating',
        ),
    ]
