# Generated by Django 3.0 on 2019-12-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191219_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='avgreview',
            new_name='avgrating',
        ),
    ]
